project:
  type: website
  output-dir: docs

website:
  title: ""
  description: "Statistics for Scientific Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: methods.qmd
        text: Methods
      - href: trends.qmd
        text: Trends
      - href: about.qmd
        text: About

format:
  html:
    theme: journal
    css: styles.css
    toc: true



